### ISSUE TITLE
How to use in a docker setup?

### ISSUE THREAD

**Issue by jewe** [pajowu/pretix-custom-css#1]
Can you please explain how to use this plugin in a smallscale docker setup?
https://docs.pretix.eu/en/latest/admin/installation/docker_smallscale.html
Thank you!

**Comment by pajowu** [comment]
The steps are the same as describes in the documentation you linked: https://docs.pretix.eu/en/latest/admin/installation/docker_smallscale.html#install-a-plugin

You only need to change the package name to this repository url when you create a custom Dockerfile
```
FROM pretix/standalone:stable
USER root
RUN pip3 install git+https://github.com/pajowu/pretix-custom-css.git
USER pretixuser
RUN cd /pretix/src && make production
```
